version: '3.4'

services:
  slogan-front:
    image: slogans-municipio-front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4300:80
      - 4343:443
    restart: always
    volumes:
      - "./certs:/etc/nginx/certs"